### ISSUE TITLE
Dimension-specific terrain handling (void tile, column tile, etc)

### ISSUE THREAD

**Issue by JohnsonJohnsonson** [sisby-folk/antique-atlas-respacks#8]
I'm currently creating a compatibility pack for the Aether, but the void tiles default to those of the end - I think it'd be cute (and functional) if I could define a custom void tile with clouds and such, purely for use in the Aether.

**Comment by sleepingdragoninn** [comment]
Makes sense - Is the biome in the aether just `minecraft:void`?

**Comment by JohnsonJohnsonson** [comment]
I believe it's done through the world generation, i.e. the empty air also has a regular biome, it just doesn't spawn any terrain. The Atlas works, because it seems to detect that there is no terrain there, but it just defaults to the End's void tile

**Comment by sleepingdragoninn** [comment]
aha! got it, let me swap titles.

**Comment by sleepingdragoninn** [comment]
closing this in favour of https://github.com/sisby-folk/antique-atlas/issues/249
